# Generated by Django 3.1.6 on 2021-07-10 16:46

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='Image',
            field=models.ImageField(help_text='SIZE 200X200', upload_to='Author/'),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Seo_Title', models.CharField(max_length=200)),
                ('Seo_Description', models.CharField(max_length=200)),
                ('Headline', models.TextField()),
                ('Image', models.ImageField(upload_to='news/%Y/%M/%D')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], default='Draft', max_length=30)),
                ('Author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='news.author')),
                ('Tag', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='news.category_tag')),
            ],
        ),
    ]
