# Generated by Django 3.1.6 on 2021-07-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210710_2216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Author'},
        ),
        migrations.AlterModelOptions(
            name='category_tag',
            options={'verbose_name': 'Category Tag'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.RenameField(
            model_name='news',
            old_name='content',
            new_name='Content',
        ),
        migrations.AddField(
            model_name='news',
            name='Slug',
            field=models.SlugField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='Date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='Image',
            field=models.ImageField(help_text='SIZE 1920X1272', upload_to='news/%Y/%M/%D'),
        ),
    ]
