# Generated by Django 3.1.6 on 2021-07-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210711_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='HomePage_Position',
            field=models.CharField(choices=[('Featured Big', 'Featured Big'), ('Featured Small', 'Featured Small'), ('Trending', 'Trending'), ('News Slide', 'News Slide'), ('News Verticle', 'News Verticle'), ('News Popular', 'News Popular'), ('Most Viewed', 'Most Viewed')], default='None', max_length=50),
        ),
    ]
