# Generated by Django 3.1.6 on 2021-07-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_homepage_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='HomePage_Position',
            field=models.CharField(choices=[('Featured Big', 'Featured Big'), ('Featured Small', 'Featured Small'), ('Trending News', 'Trending News '), ('News Horizontal', 'News Horizontal'), ('News Verticle', 'News Verticle'), ('Most Popular', 'Most Popular'), ('Most Viewed', 'Most Viewed')], default='News Verticle', max_length=50),
        ),
    ]
