# Generated by Django 3.1.6 on 2021-07-12 21:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='status',
            field=models.CharField(choices=[('Read', 'Read'), ('Unread', 'Unread'), ('Spam', 'Spam')], default='Unread', max_length=30),
        ),
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 12, 21, 38, 41, 274856)),
        ),
    ]
