# Generated by Django 3.1.6 on 2021-07-12 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20210712_2138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'default_permissions': ('change', 'delete', 'view'), 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 12, 21, 53, 24, 232205)),
        ),
    ]
